# you need to have a boiler or whatever heating system controlled by a switch for this to work
# however if you've got another HVAC then there should be no problem to control it by 
# calling respective HA services for it etc instead of switch.turn_on/off
# the key thing here is binary_sensor.thermostat which turns 'on' if a temperature 
# in a given time period is below a temperature indicated by a sensor nad 'off' if 
# the current time is outuside the heating periods
- id: 'unique_id_123213542351345234'
  alias: '[HEATING] Scheduler + Thermostat'
  description: Sensor based weekly heating scheduler
  trigger:
  - platform: time_pattern
    seconds: /60
  condition:
  - condition: template
    value_template: '{{(states("binary_sensor.thermostat") != states("switch.boiler"))}}'
  action:
  - data:
      entity_id: switch.boiler
    service_template: '{% if states("switch.boiler") == ''on'' %}switch.turn_off {%
      else %}switch.turn_on{% endif %}'
