- id: '1586688349366'
  alias: Sunny minutes during the day
  description: ''
  trigger:
  - minutes: /1
    platform: time_pattern
  condition:
  - after: sunrise
    before: sunset
    condition: sun
  - condition: state
    entity_id: weather.dom
    state: sunny
  action:
  - data: {}
    entity_id: input_number.sunny_minutes
    service: input_number.increment
- id: '1586688527031'
  alias: Turn on boiler of the day wasn't sunny enough
  description: ''
  trigger:
  - at: '20:00:00'
    platform: time
  condition:
  - below: '240'
    condition: numeric_state
    entity_id: input_number.sunny_minutes
  action:
  - data: {}
    entity_id: switch.boiler
    service: switch.turn_on
